### ISSUE TITLE
Not creating interface for OVS to use

### ISSUE THREAD

**Issue by edsealing** [John-Lin/ovs-cni#10]
Kubernetes version: 1.8.3
OVS Version:  2.8.1

I have multus working with OVS-CNI as outlined in the README.

When I create a new Pod, I can see it attempt to create the associated bridge/port, but OVS is throwing the error:

## Output from `ovs-vsctl show`
```
Port "vethf18e312f"
            Interface "vethf18e312f"
                error: "could not open network device vethf18e312f (No such device)"
```

## /etc/cni/net.d/10-multus.conf

```
{
"name": "minion-cni-network",
"type": "multus",
"kubeconfig": "/root/.kube/config",
"delegates": [
   {
    "type": "flannel",
    "hairpinMode": true,
    "masterplugin": true
   },
   {
    "type": "ovs",
    "vtepIPs":[
        "10.0.0.3"
    ],
   "ipMasq": true,
   "ipam":{
      "type":"host-local",
      "subnet":"10.244.0.0/16",
      "rangeStart":"10.244.1.10",
      "rangeEnd":"10.244.1.150",
      "routes":[
         {
            "dst":"0.0.0.0/0"
         }
      ],
      "gateway":"10.244.1.1"
   }
    
   }
]
}
```

**Comment by John-Lin** [comment]
@edsealing Hi, we've fixed this issue in the branch [johnlin/del-ovs-port](https://github.com/John-Lin/ovs-cni/tree/johnlin/del-ovs-port)

**Comment by John-Lin** [comment]
If you want to extend the multiple network interfaces with kubernetes please see the instructions here https://github.com/John-Lin/ovs-cni/tree/johnlin/del-ovs-port/deployments/kubernetes#extend-the-multiple-network-interfaces-with-ovs-cni

**Comment by edsealing** [comment]
Thanks. It looks like my problem was incorrect syntax in the Network resources.

Does the ovs plugin currently support assigning vlan tags to the port at instantiation?
